In [ ]:
from CNNectome.validation.organelles.segmentation_metrics import Evaluator,EvaluationMetrics,display_name,sorting
import h5py
import numpy as np
import csv
import os
import matplotlib
%matplotlib inline 
from matplotlib import pyplot as plt
import pandas as pd
import re
import zarr
import tifffile
import seaborn
import pandas
from scipy.ndimage import label, distance_transform_edt
from CNNectome.utils.compute_label_distribution import distance
import scipy

In [2]:
from annotator_metrics.util.doc_io import MaskInformation
mi = MaskInformation()
for row in mi.rows:
    print(row.original_coordinates)

[5651, 230, 3450]
[5901, 650, 6670]
[7426, 245, 3840]
[4000, 200, 7800]
[4333, 224, 7068]
[0, 2000, 1600]
[4761, 4952, 6493]
[7000, 4151, 9017]
[4275, 7350, 5700]
[4443, 5716, 3322]


In [1]:
from annotator_metrics.util.doc_io import MaskInformation
from annotator_metrics.src.preprocessing import copy_data
mi = MaskInformation()
print(mi.rows)
copy_data(group = "group1", output_base_path="/groups/cosem/cosem/ackermand/annotation_and_analytics/tmp/")

[<annotator_metrics.util.doc_io.Row object at 0x7f4a69f563c8>, <annotator_metrics.util.doc_io.Row object at 0x7f4a69890080>, <annotator_metrics.util.doc_io.Row object at 0x7f4a69f8ab00>, <annotator_metrics.util.doc_io.Row object at 0x7f4a69890198>, <annotator_metrics.util.doc_io.Row object at 0x7f4a69890dd8>, <annotator_metrics.util.doc_io.Row object at 0x7f4a6984f518>, <annotator_metrics.util.doc_io.Row object at 0x7f4a6984fc18>, <annotator_metrics.util.doc_io.Row object at 0x7f4a69856358>, <annotator_metrics.util.doc_io.Row object at 0x7f4a6984fef0>, <annotator_metrics.util.doc_io.Row object at 0x7f4a6984f4a8>]
predictions (400, 400, 400)
refinements (400, 400, 400)
03 predictions
03 refinements
predictions (400, 400, 400)
08 predictions
predictions (400, 400, 400)
refinements (400, 400, 400)
ariadne (400, 400, 400)
09 predictions
09 refinements
09 ariadne
predictions (400, 400, 400)
10 predictions


In [2]:
from annotator_metrics.util.doc_io import MaskInformation
mi = MaskInformation()
print(mi.rows[0].organelle_info)


{'mito_mem ': 3, 'mito_lumen ': 4, 'mito': 0}


In [3]:
import numpy as np
a=np.random.random((4,4,4))

In [7]:
print(a[1:3,1:3,1:3])

[[[0.29667459 0.14585225]
  [0.93038333 0.71463271]]

 [[0.04604659 0.92718152]
  [0.80627626 0.55996372]]]


In [1]:
import zarr
organelle_result_name = "mito"
organelle_result_path = "/nrs/cosem/pattonw/training/finetuning/jrc_mus-liver/liver_latest_setup04_many_masked_6-1_100000.n5"
zarr_file = zarr.open(organelle_result_path, mode = "r")
if os.path.isdir(f"{organelle_result_path}/volumes"):
    zarr_file = zarr_file["volumes"][organelle_result_name]
    print("v")
    if os.path.isdir(f"{organelle_result_path}/volumes/s0"):
        zarr_file = zarr_file["s0"]
        print("s")
else:
    zarr_file = zarr_file[organelle_result_name]
    print("n")


v


In [1]:
from annotator_metrics.src.metrics_evaluations import calculate_all_to_all

all_to_all_by_crop= calculate_all_to_all("group1","/groups/cosem/cosem/ackermand/annotation_and_analytics/tmp/")

array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])